name: notepad
description: "A simple Note Pad bundle for ARI."
publish_to: "none"
version: 0.1.10+13

environment:
  sdk: ^3.11.1

dependencies:
  ari_plugin:
    git:
      url: https://github.com/rightsna/ARIAgent.git
      ref: main
      path: ari-framework/plugin
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
